image: node:24

pipelines:
  default:
    - step:
        name: Release
        script:
          - corepack enable
          - pnpm install --frozen-lockfile
          - pnpm run validate
          - pnpm run release
