image: node:22

pipelines:
  default:
    - step:
        name: Release
        script:
          - npm ci --prefer-offline --no-audit
          - npm run validate
          - npm run release
          - git push origin main --follow-tags
