image: node:20

pipelines:
  default:
    - step:
        name: Publish
        script:
          - npm ci --prefer-offline --no-audit
          - npm run publish
          - npm run skip-ci
          - git push --follow-tags origin main
